### ISSUE TITLE
Infografia Actividad 7

### ISSUE THREAD

**Issue by HECTOR-KDM02** [SistemasTecTlaxiaco/infografia-de-hilos-HECTOR-KDM02#2]
[Infografía Trabajo Freelance Autónomo Simple Pastel.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-HECTOR-KDM02/files/15082057/Infografia.Trabajo.Freelance.Autonomo.Simple.Pastel.pdf)

INFOGRAFIA

**Comment by Kim-Mendoza3** [comment]
calificacion 19

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
